version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: jammy
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        HTTP_PROXY: ${http_proxy:+http://172.17.0.1:1080}
    container_name: clean_architecture_rust
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    user: ${USERNAME}

    ports:
      - 8888:8888

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432

volumes:
  postgres-data: